name: test

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.19.0'

      - name: Checkout
        uses: actions/checkout@v3

      - name: Unit tests
        run: make test

      - uses: codecov/codecov-action@v3
        with:
          files: cover.out
